### ISSUE TITLE
Not updating at the selected time

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/spotkin_flutter#61]
I had set my update time to 2am but I noticed it actually updated at 11pm when it updated on me in the middle of listening. I checked the next night and same thing - 11pm. 

So yesterday I changed it to 9am and this morning when I went to check - it was already updated before then. From looking at the Spotify "date added" column it seems it was updated at 3am. 

![image](https://github.com/user-attachments/assets/216b7951-8b68-475d-86c0-189875f343bb)

Mel also mentioned hers being off. She has hers set for 10pm and it  updated today at 9:45am while she was listening. She sent this screenshot. The current song playlist was from her previous list and you can see it's not on the updated list. 

https://github.com/user-attachments/assets/12bf04c0-70b6-4c18-8fec-3e69ca119d5d

**Comment by riverscuomo** [comment]
@KCreek1 thanks. should be fixed now if you set the scheduled time again.
