### ISSUE TITLE
Updating at incorrect time

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/spotkin_flutter#63]
Mel informed me that post fix, the update times are still incorrect for her.  We tracked our times over the weekend:

Mel scheduled time versus real:
8/16 - 10am : between 8-8:30am
8/17 - 12pm : already by 9:29am
8/18 - 1pm : 8am

Kristina scheduled time versus real:
8/16 - 6pm : 6pm (watched it update)
8/17 - 2am : 1:30am
8/18 - 2am : 1:30am

Definitely a bigger difference for hers. The only reason I realized my early morning time was updating a half hour earlier is the date added on Spotify changed while I was watching later in the day on Saturday.  Then I confirmed on Sunday. Maybe it's not recognizing local time with all the timezones?

**Comment by riverscuomo** [comment]
Server has 
Mel Radio at 11pm GMT.
Kristina at 8am GMT

might this be helpful? https://www.epochconverter.com/

**Comment by taylorlee3** [comment]
a matrix of their local time (their scheduled update time) and what that would be in GMT. what the server has them down as in GMT and what time it was actually updated in their local time and their GMT

| Name | Sched Update Time (local)| Sched Update Time (GMT)| Real Update Time (local)| Real Update Time (GMT) | Server time (GMT)|
|--------|--------|--------|--------|--------|--------|
| **Kristina** | 6 pm MDT | 12 am GMT| 6 pm MDT |  12 am GMT| 8 am GMT|
| | 2 am MDT | 8 am GMT| 1:30 am MDT | 7:30 am GMT| 8 am GMT|
| | 2 am MDT | 8 am GMT| 1:30 am MDT | 7:30 am GMT| 8 am GMT|
| **Mel** | 10 am ACST | 12:30 am GMT| 8-8:30 am ACST | 10:30-11 pm GMT| 11 pm GMT|
| | 12 pm ACST | 2:30 pm GMT| by 9:29 am ACST |11:59 pm GMT| 11 pm GMT|
| | 1 pm ACST | 3:30 GMT| 8 am ACST | 10:30 pm GMT| 11 pm GMT|

**Comment by riverscuomo** [comment]
@KCreek1 I saw Kristina's Radio just updated at 16 GMT and was scheduled at 16 GMT. Is that not what you see in your settings?

![image](https://github.com/user-attachments/assets/5bab76a0-6ec0-4097-ae26-63d7a09de596)

**Comment by KCreek1** [comment]
@riverscuomo Yes.  That's accurate.  I was testing some more on the issue of both playlists not updating so I changed it to later morning so I could watch when they updated. And Kristina's radio did update at the correct time today.

Also, Mel's did not update at all.
