### ISSUE TITLE
new spotkin sounds

### ISSUE THREAD

**Issue by taylorlee3** [riverscuomo/spotkin_flutter#72]
on press happier coo
fail - unhappy coo

**Comment by riverscuomo** [comment]
Did you ever find some more sounds?

**Comment by taylorlee3** [comment]
yeah, i put them in assets.

**Comment by riverscuomo** [comment]
I'm not seeing the here: https://github.com/riverscuomo/spotkin_flutter/tree/main/assets/sounds

Did you `git add` them?

**Comment by taylorlee3** [comment]
i think so... they're on a branch that hasn't been merged though: 'origin/72-new-spotkin-sounds'

**Comment by riverscuomo** [comment]
@taylorlee3 should this be closed?
