### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by KCreek1** [riverscuomo/spotkin_flutter#75]
Playlist did not update at scheduled time. 

Manual updates are not working either. I tried earlier this am and just a few minutes ago. 

Mel reported same for her. 

![image](https://github.com/user-attachments/assets/b311b7ed-b9c7-40fd-a90d-f8720e5e063b)

https://github.com/user-attachments/assets/6544475c-815f-445d-9f6d-48e02991f18f

**Comment by riverscuomo** [comment]
@KCreek1 yeah I'm in the middle of implementing a database so we can sync our spotkins across devices.

**Comment by KCreek1** [comment]
Ok. Sounds good.

**Comment by KCreek1** [comment]
Updated as scheduled.
