### ISSUE TITLE
Daylight Saving Affected Playlist Update

### ISSUE THREAD

**Issue by Mel01000001** [riverscuomo/spotkin_flutter#83]
I have my Scheduled Update Time set to 7.00am.  Usually it will update at 7.30am.  As can be seen in this discussion.  I have no actual screenshots, but note the timestamps as @KCreek1 and I regularly check in with each other regarding updates.

![Screenshot_20241006_161911_Discord](https://github.com/user-attachments/assets/652442fa-d726-456a-ad92-20573b9f8ba8)
![Screenshot_20241006_161949_Discord](https://github.com/user-attachments/assets/0ee90a8d-0f39-4641-968d-b063dccbc6c8)

Today, Daylight Saving started (so my local time went forward an hour).  My playlist updated at 8.30am and when I looked at the settings, it was now set to 8.00am, which I had not changed.

Again for timestamp purposes.

![Screenshot_20241006_164809_Discord](https://github.com/user-attachments/assets/0093f908-a43b-4970-b505-0cdc2dd18820)

![Screenshot_20241006_164717_Discord](https://github.com/user-attachments/assets/e5a51287-91e6-4142-bfbe-cab97504aaae)

Spotkin now showing 8.00am.

![Screenshot_20241006_125243_Chrome](https://github.com/user-attachments/assets/3a5422c7-581d-46c0-ad1a-b8d6408ce6fe)

I tested a scheduled update this afternoon and it updated as per usual.  Was set for 3.00pm and updated at 3.30pm.

**Comment by KCreek1** [comment]
I asked chat about the time conversion issue with DST and the half hour discrepancy Mel experiences. It may be a relatively easy fix of adding the minutes argument to the DateTime object  in localToUtc and utcToLocal. 

If I understood it correctly.

**Comment by riverscuomo** [comment]
I think the Heroku scheduler runs some time within the hour your request.
