### ISSUE TITLE
clarify acousticness

### ISSUE THREAD

**Issue by riverscuomo** [riverscuomo/spotkin_flutter#92]
should be bringing in around 100 tracks, but I'm getting 8.

https://open.spotify.com/playlist/0nKvNNM4fY8keHvpTxqkXs

![image](https://github.com/user-attachments/assets/b58ce06b-571c-4de0-8058-00cb17e463f6)

**Comment by riverscuomo** [comment]
process_job: The Big Pool Radio
Getting tracks from the playlists earmarked for the The Big Pool Radio playlist...
spotify object: Spotify
spotify object: Spotify
- sampling up to 10 Spotify tracks from the playlist 'THE BIG POOL OF TRACKS TO LISTEN TO'... spotify object: Spotify- sampling up to 10 Spotify tracks from the playlist '0n Repeat'...


spotify object: Spotify
- sampling up to 10 Spotify tracks from the playlist 'the definitive collection 5pGoJFq4DTizMWrXvzPyyr'...
spotify object: Spotify
- sampling up to 2 Spotify tracks from the playlist 'Generally a Great Playlist'... 
- sampling up to 2 Spotify tracks from the playlist '❄️ Winter '23/'24 (Dec-Feb)'...
spotify object: Spotify
spotify object: Spotify
- sampling up to 2 Spotify tracks from the playlist '💨 The George Tavern Playlist'...
spotify object: Spotify- sampling up to 2 Spotify tracks from the playlist 'danielwilmslow + Katie'...

spotify object: Spotify
spotify object: Spotify
- sampling up to 2 Spotify tracks from the playlist 'Lucas + Katie'...
- sampling up to 1 Spotify tracks from the playlist 'Rockabilly Numbers'...
- sampling up to 1 Spotify tracks from the playlist 'kool & green'...
HTTP Error for GET to https://api.spotify.com/v1/playlists/37i9dQZF1EJFOCoNRibOTW/tracks with Params: {'limit': 100, 'offset': 0, 'fields': None, 'market': None, 'additional_types': 'track'} returned 404 due to Resource not found
Playlist Lucas + Katie generated an exception: http status: 404, code:-1 - https://api.spotify.com/v1/playlists/37i9dQZF1EJFOCoNRibOTW/tracks?limit=100&offset=0&additional_types=track:
 Resource not found, reason: Nonespotify object: Spotify

- sampling up to 1 Spotify tracks from the playlist 'APOLLO RELEASES'...
HTTP Error for GET to https://api.spotify.com/v1/playlists/37i9dQZF1EJw5qNKYHTSH1/tracks with Params: {'limit': 100, 'offset': 0, 'fields': None, 'market': None, 'additional_types': 'track'} returned 404 due to Resource not found
Playlist danielwilmslow + Katie generated an exception: http status: 404, code:-1 - https://api.spotify.com/v1/playlists/37i9dQZF1EJw5qNKYHTSH1/tracks?limit=100&offset=0&additional_types=track: 
 Resource not found, reason: Nonespotify object: Spotify

- sampling up to 1 Spotify tracks from the playlist '2002-2007 Busted/McFly'...
HTTP Error for GET to https://api.spotify.com/v1/playlists/6EJqs0lFXMxeWDaRwXrQMo/tracks with Params: {'limit': 100, 'offset': 0, 'fields': None, 'market': None, 'additional_types': 'track'} returned 404 due to Resource not found
spotify object: Spotify
Playlist 0n Repeat generated an exception: http status: 404, code:-1 - https://api.spotify.com/v1/playlists/6EJqs0lFXMxeWDaRwXrQMo/tracks?limit=100&offset=0&additional_types=track:
 Resource not found, reason: None
- sampling up to 1 Spotify tracks from the playlist 'best of WEEZER'...
spotify object: Spotify
- sampling up to 1 Spotify tracks from the playlist 'best of KING GIZZARD'...
spotify object: Spotify
- sampling up to 1 Spotify tracks from the playlist 'best of THE REBEL'...
spotify object: Spotify
- sampling up to 1 Spotify tracks from the playlist 'An Education in Real Music: Justin Bieber'...
spotify object: Spotify
- sampling up to 1 Spotify tracks from the playlist 'An Education in Real Music: BMTH'...
spotify object: Spotify
- sampling up to 1 Spotify tracks from the playlist 'pop punk 4eva'...
spotify object: Spotify
- sampling up to 2 Spotify tracks from the playlist '🖤 craik david's l0ser kid playlist'...
spotify object: Spotify
- sampling up to 2 Spotify tracks from the playlist '00's - Best Playlist Ever'...
spotify object: Spotify
- sampling up to 10 Spotify tracks from the playlist 'THE BIG POOL [OLD]'...
spotify object: Spotify
- sampling up to 2 Spotify tracks from the playlist 'Discover Weekly'...
spotify object: Spotify
- sampling up to 5 Spotify tracks from the playlist 'melomania'...
spotify object: Spotify
- sampling up to 5 Spotify tracks from the playlist 'Hot New Bands'...
spotify object: Spotify
- sampling up to 2 Spotify tracks from the playlist 'BBC Radio 6 Music Playlist'...
spotify object: Spotify
- sampling up to 5 Spotify tracks from the playlist 'The Official Chart UK Top 40'...
spotify object: Spotify
- sampling up to 1 Spotify tracks from the playlist 'King Rizzard & The Kizard Crizard'...
spotify object: Spotify
- sampling up to 5 Spotify tracks from the playlist 'emo right now'...
spotify object: Spotify
- sampling up to 2 Spotify tracks from the playlist 'The Neu Playlist'...
spotify object: Spotify
- sampling up to 2 Spotify tracks from the playlist 'NME's New Bangers'...
spotify object: Spotify
spotify object: Spotify
- sampling up to 1 Spotify tracks from the playlist 'UK House Music'...
- sampling up to 2 Spotify tracks from the playlist 'The BSM Office Playlist'...
spotify object: Spotify
- sampling up to 1 Spotify tracks from the playlist 'Kerrang! Chart'...
spotify object: Spotify
- sampling up to 1 Spotify tracks from the playlist 'Rivers Radio'...
spotify object: Spotify
- sampling up to 1 Spotify tracks from the playlist 'On Repeat'...
tracks: 85
['1LYNjTxJTxBBw4MsXqsyI2', '4m7AfmOYn9dQjYVqWFufBS', '6b3sztg64sk7iiKzjLGT2G', '7nVIHoGvdlUYCGXklgzqaM', '3WB5Q4VtBloq0kDTpEEwLy', '5dE7Fyz6OYLBlm0oHphfyL', '4pFo70BuXv6FjLVD4bAjRg', '7szLTdXf2XAcWopTqvIrbc', '45dfCQFmGcGn1cNTkukKe3', '544xcMdny7JqmMbkVxHoiX', '19d6ySq61vARL7hayVuoWZ', '0I3m2omTqOTK1sexmLb5E3', '1C2TixzCNkUiSqJqkOckor', '6uJqeSFDtBKOUKALrvlRHG', '1oTHySpvYOZrfe033J418Y', '4y3KiwLcKLaKPHf6tH4s7F', '4C0kha9l7unfzrkt8F0aNF', '2C5jGbR23YLonV7Lton6fV', '3HVWdVOQ0ZA45FuZGSfvns', '7GjFQsuOpyxPOPAKpuFX10', '4MZfdXX0OnqH3tGxEsm1nU', '0Dr7ffzGkYkNErJDtpBrGj', '6vNhNghDgxY8o4RCRFAwqA', '2zPEvSxzmCYrpgNn1ZhW4U', '1L5esFBo3aYAUnXtsHuzWi', '7LRBfIOKLb09y0i0THx0L1', '0zuMZmRQBp65CNS6WfzEYl', '3ipl8FVrOq9PoTUVm2ogXv', '2oADPwknKEfMtwpMnr7xfg', '6xrTHtSg2SDBLilLxhbhof', '3QaPy1KgI7nu9FJEQUgn6h', '5vNRhkKd0yEAg8suGBpjeY', '0UYnhUfnUj5adChuAXvLUB', '6HLwtE0bB2kRfpeVlXmDVa', '59BSXqdDDiNnt79NuG5mIM', '2NtdqCfyAe6Jqq4o5cFAo4', '7jv7BrGJl1sk6r3a6qNhFP', '4FcQeSZNS22TDJbjm5qw3I', '5JV1b92v3C6Css76envcRx', '2E6m4fRCHlccJqVEHKeIIF', '5uA9Ge1b2pipaONSF6cqnZ', '5lcEVADWz6YKvpGJfrQfba', '6Ciqo08MA2NF2lgWiNi8u4', '4hJ5jWbqstdYt555NhdtNk', '1PUioUtzq6HR2o3JanrmX5', '6mX4YzF35p8r2gLbYN6eJ0', '3FgntAOZyZGC7IhkUg142e', '5GYlldi6Qa1Px83vRKCuDj', '0PkriCeqOJvh9QNvfMka7w', '71VFHN459tdGGWOLpMdYMi', '0XGV6cr7MPIiLjxJ7JbMEQ', '6bfvJmIShenDFix2g37t1S', '1gB04M0xEvfPGQWGzbD9dY', '6RGVgepzeIBgl4iFQyTayh', '7rVC99NBBSpGPEtxv0M93e', '4B25pnx5okJSEmQpYI6QIF', '4xiyq1iRdsxuU1BPUJ490Z', '4IRW2sC0FPr2Rz4ewFIFQr', '73AxZuHupzShJmzBeH0RnW', '3lljC5fVbPexiJasdTKTUb', '3lnjFENd7rHxPYM9b964Md', '3pvOdS9kIz3LL0UoRVsabS', '18vdhCWxqPohnPwicDi3Xr', '07Sm4SlYGZ4CRSxgwP3hUr', '4JHg4nNYUJQ5HULcCmI18R', '1d8FxchId0PXnNqc9allBO', '6bMq5b9TNkWD9g4V5xr9wS', '6RCJa37P65U7uCm6oyxY3J', '6WOEiDqorXWXaLxxqLnclO', '6hzwfFKrTabeUsW5SWti17', '0Yoi56zu2iturSm4366NUF', '3JsydWaf2Ev4ehaLUjj3SY', '1wxt8kslSQNRrx2qJDXRtv', '3pF6D6cIb1xz5u6Ln5mtpN', '1zwsIjVrjf2b76z1h3aa8k', '2IN0m27CmIyZ8TNNohp3I6', '1D1M805zV8DwhYXsvJdQZx', '1Wi1XpdZzGVIdRTzlTrIEF', '4zI63FNhcQp2ueW1c2XOgL', '7qhoCDOqTj8Inlh2BVP0Gk', '5FtasByO6sDnqnG3mSoVjH', '47TvC8OJW63nidqtTnky5J', '17phhZDn6oGtzMe56NuWvj', '0eDt5h1rohZSvqW7w1HFmx', '0OA00aPt3BV10qeMIs3meW']
- returning get_audio_features track ids...
- returning artist genres for artist ids...
- Hark! The Herald Angels Sing by Busted banned for low acousticness: 6.78
- Pallor Tricks by Cola banned for low acousticness: 1.17
- GPTYPPTP by sprgrs banned for low acousticness: 13.8
- Autopilot by Weezer banned for low acousticness: 6.2700000000000005
- I'm a New Person, Ma'am by Country Teasers banned for low acousticness: 22.1
- Fried by King Gizzard & The Lizard Wizard banned for low acousticness: 17.8
- Isolated Love (feat. Travis Barker) by Bishop Briggs banned for low acousticness: 10.9
- Eye Sore by Bay Faction banned for low acousticness: 0.20500000000000002
- One More Day by Umarells banned for low acousticness: 0.15
- WYA by Leah Kate banned for low acousticness: 8.780000000000001
- I Can't Wait Until I'm Old by Flip Top Head banned for low acousticness: 12.6
- Yard by Esme Emerson banned for low acousticness: 5.59
- Really Good Day by SNATO banned for low acousticness: 2.44
- New High by dust banned for low acousticness: 0.11399999999999999
- Getting Good by Lazy Day banned for low acousticness: 0.0448
- Weapons of Mass Seduction by WOOZE banned for low acousticness: 0.00879
- Chelsea Smile by Bring Me The Horizon banned for low acousticness: 0.0036100000000000004
- I Don't Care (with Justin Bieber) by Ed Sheeran banned for low acousticness: 9.02
- Lona by SEX SHOP MUSHROOMS banned for low acousticness: 0.40299999999999997
- Ohio All The Time by Momma banned for low acousticness: 1.04
- Hey Yah! by Eletto banned for low acousticness: 22.7
- Our Secret by Beat Happening banned for low acousticness: 10.4
- Last Train Home by lostprophets banned for low acousticness: 0.0674
- Hotline to Memory by Praise banned for low acousticness: 0.0213
- Sophomore by Weatherman banned for low acousticness: 9.82
- All My Freaks by Divorce banned for low acousticness: 1.73
- Bangin' on the Freeway - Bonus Track by Kim Gordon banned for low acousticness: 0.719
- Espresso by Sabrina Carpenter banned for low acousticness: 10.8
- Sympathy is a knife featuring ariana grande by Charli xcx banned for low acousticness: 9.62
- WILDFLOWER by Billie Eilish banned for low energy: 24.7
- APT. by ROSÉ banned for low acousticness: 2.83
- The Times by She's In Parties banned for low acousticness: 0.13699999999999998
- Paith Own by a Lesser Version banned for low acousticness: 0.297
- Snow White by Fake A Smile banned for low acousticness: 0.0545
- The Painting of the Bay by W. H. Lung banned for low acousticness: 2.16
- TORMENTOR by HONESTY banned for low acousticness: 36.8
- Fall In Love (feat. Odeal) by JayO banned for low acousticness: 44.1
- EZPZ by Man/Woman/Chainsaw banned for low acousticness: 0.123
- Death Lurking (feat. Izzy Da Fonseca) by Lip Critic banned for low acousticness: 1.6500000000000001
- Headspace by cruush banned for low acousticness: 0.803
- She's Leaving You by MJ Lenderman banned for low acousticness: 0.378
- What's Mine by stepover banned for low acousticness: 0.0712
- What Have You Done? by Korda Korder banned for low acousticness: 26.5
- Angel Food by BEEFCAKE banned for low acousticness: 8.64
- Plant Pot Song by Indoor Foxes banned for low acousticness: 6.3100000000000005
- Serotonin by Covey banned for low acousticness: 3.2300000000000004
- the CIA by glass beach banned for low acousticness: 0.129
- tequila redbull by Equipment banned for low acousticness: 3.2800000000000002
- caffeine cops by Khaki Cuffs banned for low acousticness: 2.12
- exes by Tate McRae banned for low acousticness: 16.6
- It Is What It Is by Out Of Love banned for low acousticness: 0.00274
- 2 + 2 = 5 by Rockabye Baby! banned for low energy: 22.8
- Close To Me by The Cure banned for low acousticness: 7.449999999999999
- Delfina by Enzo Cervo banned for low acousticness: 41.3
- 泡沫の空、永遠の街 by paranoid void banned for low acousticness: 0.6839999999999999
- Buses/No Buses by Bear Vs. Shark banned for low acousticness: 0.015300000000000001
- C'mon, C'mon by One Direction banned for low acousticness: 1.5
- Playing With Fire by N-Dubz banned for low acousticness: 14.099999999999998
- Dilemma by Nelly banned for low acousticness: 20.9
- Boost Up by FISHER banned for low acousticness: 0.0897
- What You Know by Two Door Cinema Club banned for low acousticness: 0.0673
- Are You Free Tonight? by Pardoner banned for low acousticness: 0.00276
- Crank It Up by Hadouken! banned for low acousticness: 3.95
- B Boys Anthem by B Boys banned for low acousticness: 0.675
- Backwash by Gilla Band banned for low acousticness: 1.24
- Crush by Pendulum banned for low acousticness: 0.00134
- Shine On by Your Demise banned for low acousticness: 0.000366
- Confident by Justin Bieber banned for low acousticness: 11.4
- to some i'm genius by snow ellet banned for low acousticness: 0.696
- Good Morning, Captain - Remastered by Slint banned for low acousticness: 5.779999999999999
- Communication by Disq banned for low acousticness: 0.303
- On The Floor by THUS LOVE banned for low acousticness: 0.28400000000000003
- Burning by Tems banned for low acousticness: 37.8
- Soup by Remi Wolf banned for low acousticness: 1.03
- Lewis in Pomona by Underworld banned for low acousticness: 8.58
- Julian Casablancas (I Wanna Rock a Pair Like) by Slumber banned for low acousticness: 0.35100000000000003
- High Beaming by Skegss banned for low acousticness: 0.136
- Mercy Benz by P.H.F. banned for low acousticness: 6.76
- Lose Control by Teddy Swims banned for low acousticness: 19.900000000000002
- Graveyard Shift by Chaos Reigns banned for low acousticness: 0.0602
- Big Dawgs by Hanumankind banned for low acousticness: 2.35
spotify.user_playlist_replace_tracks with an empty list
rcuomo
4
HTTP Error for PUT to https://api.spotify.com/v1/playlists/0nKvNNM4fY8keHvpTxqkXs/tracks with Params: {} returned 404 due to Resource not found

**Comment by riverscuomo** [comment]
Higher values (closer to 100) indicate that a track has strong acoustic qualities, meaning it likely features traditional acoustic instruments (like guitar, piano, or vocals without heavy electronic processing).
Lower values (closer to 0) suggest that a track is more likely to be produced electronically or features heavier processing, synthetic sounds, or amplified instrumentation.

**Comment by taylorlee3** [comment]
next to acousticness, add info button that has a bottom pop up with info in RC comment above

**Comment by KCreek1** [comment]
Is this available to work on or is it assigned already?

If it's already assigned, please disregard. 

I think if I wrap the title in a row like this then the info button should appear right next to the title: or I can add adjust to put it on the far right.

 ![image](https://github.com/user-attachments/assets/2a1325ca-6a9e-4f68-88f9-ec3174df3557)

And I put the following:

A class for AcousticnessInfoButton in info_button.dart

A function in bottom_sheets.dart

And build sheet in spotkin_info_content.dart

**Comment by riverscuomo** [comment]
@KCreek1 I asked @taylorlee3 to do it yesterday but I don't think she's started and I don't think she'd mind if you did it. 

Just curious, are you able to run this locally to see what you're doing?

**Comment by KCreek1** [comment]
That's where I run into an issue. I'm not entirely sure how to run locally. When I try to run it gives me an error about not loading the json file.

**Comment by KCreek1** [comment]
I'm trying to figure it out but I'm kind of running in circles. So if you can point me in the right direction.

**Comment by riverscuomo** [comment]
It's a good goal for us but it's going to be difficult. I'm not sure how to run the spotkin flutter app without also running the spotkin python flask server which is connected to the database. That's a whole other repo. A pro would set up a dev environment with it's own database. I'll keep this in mind.

**Comment by KCreek1** [comment]
That actually makes me feel a little better cause I've been trying to figure it out. That's pretty much the answer I've found.

**Comment by KCreek1** [comment]
The best I've come up with right now is ask chat to show me a render of what I put.

**Comment by riverscuomo** [comment]
That's a cool idea. I never tried that.
