### ISSUE TITLE
Remove spotify logo from spotkin image

### ISSUE THREAD

**Issue by riverscuomo** [riverscuomo/spotkin_flutter#97]

**Comment by taylorlee3** [comment]
thioughts?
![spotkin_cropped](https://github.com/user-attachments/assets/e6e8fea7-5377-4c80-bb77-0279d0ad3575)

**Comment by riverscuomo** [comment]
@taylorlee3 can you paint over the logo on his chest a little more?

**Comment by taylorlee3** [comment]
how's this?
![Screenshot 2024-12-03 161341](https://github.com/user-attachments/assets/1e938dc1-b08a-4012-8573-fd46cdbaae0e)

**Comment by riverscuomo** [comment]
cool
